//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tikshuv.Properties {
    using System;
    

    //  A strongly-typed resource class, for looking up localized strings, etc.

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        

        //  Returns the cached ResourceManager instance used by this class.

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tikshuv.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        

        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
 
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        

        //  Looks up a localized resource of type System.Drawing.Bitmap.

        internal static System.Drawing.Bitmap alertness {
            get {
                object obj = ResourceManager.GetObject("alertness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
 
        //   Looks up a localized resource of type System.Drawing.Bitmap.

        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        //Looks up a localized resource of type System.Drawing.Bitmap.

        internal static System.Drawing.Bitmap current_mission {
            get {
                object obj = ResourceManager.GetObject("current_mission", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
     
        //Looks up a localized resource of type System.Drawing.Bitmap.
       
        internal static System.Drawing.Bitmap Deposit {
            get {
                object obj = ResourceManager.GetObject("Deposit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        
        //Looks up a localized resource of type System.Drawing.Bitmap.
       
        internal static System.Drawing.Bitmap Equipment_management {
            get {
                object obj = ResourceManager.GetObject("Equipment_management", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        
        //Looks up a localized resource of type System.Drawing.Bitmap.

        internal static System.Drawing.Bitmap fildemissions {
            get {
                object obj = ResourceManager.GetObject("fildemissions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        //  Looks up a localized resource of type System.Drawing.Bitmap.

        internal static System.Drawing.Bitmap Full_screen {
            get {
                object obj = ResourceManager.GetObject("Full_screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        //Looks up a localized resource of type System.Drawing.Bitmap.
     
        internal static System.Drawing.Bitmap inventory_management {
            get {
                object obj = ResourceManager.GetObject("inventory_management", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        


 
        internal static System.Drawing.Bitmap logsout {
            get {
                object obj = ResourceManager.GetObject("logsout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static System.Drawing.Bitmap missions {
            get {
                object obj = ResourceManager.GetObject("missions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static System.Drawing.Bitmap network_vid {
            get {
                object obj = ResourceManager.GetObject("network_vid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static System.Drawing.Bitmap network_vid_background {
            get {
                object obj = ResourceManager.GetObject("network_vid_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static System.Drawing.Bitmap new_mission {
            get {
                object obj = ResourceManager.GetObject("new_mission", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static System.Drawing.Bitmap new_object {
            get {
                object obj = ResourceManager.GetObject("new_object", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
  
        internal static System.Drawing.Bitmap NewMissionIcon {
            get {
                object obj = ResourceManager.GetObject("NewMissionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static System.Drawing.Bitmap Promotional {
            get {
                object obj = ResourceManager.GetObject("Promotional", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static System.Drawing.Bitmap repeat_missions {
            get {
                object obj = ResourceManager.GetObject("repeat_missions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap reports {
            get {
                object obj = ResourceManager.GetObject("reports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static System.Drawing.Bitmap small_screen {
            get {
                object obj = ResourceManager.GetObject("small_screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static System.Drawing.Bitmap soldier1 {
            get {
                object obj = ResourceManager.GetObject("soldier1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static byte[] template {
            get {
                object obj = ResourceManager.GetObject("template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        

        internal static System.Drawing.Bitmap warehouse {
            get {
                object obj = ResourceManager.GetObject("warehouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
